name: Sync gki-android14-6.1-dev from simonpunk

on:
  workflow_call:

jobs:
  call-sync:
    uses: ./.github/workflows/sync-upstream.yml
    with:
      upstream_repo: https://gitlab.com/simonpunk/susfs4ksu.git
      upstream_branch: gki-android14-6.1-dev
      local_branch: gki-android14-6.1-dev
