name: Sync gki-android12-4.14 from simonpunk

on:
  workflow_call:

jobs:
  call-sync:
    uses: ./.github/workflows/sync-upstream.yml
    with:
      upstream_repo: https://gitlab.com/simonpunk/susfs4ksu.git
      upstream_branch: kernel-4.14
      local_branch: kernel-4.14
